---
abstract: 'Redis Model Class'
author:
  - 'Pavel Shaydo <zwon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-Redis
no_index:
  directory:
    - t
    - inc
  file:
    - README.pod
requires:
  Catalyst: 5.9
  RedisDB: 1.00
  Test::More: 0.94
resources:
  bugtracker: https://github.com/trinitum/perl-Catalyst-Model-Redis/issues
  homepage: https://github.com/trinitum/perl-Catalyst-Model-Redis
  license: http://dev.perl.org/licenses/
  repository: git://github.com/trinitum/perl-Catalyst-Model-Redis
version: 0.02
